pollster/polls/urls.py
from django.urls import path

from . import views

app_name='polls'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:question_id>/',views.detail,name='detail')
]

pollster/pollster/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
]

pollster/polls/models.py
from django.db import models

# Create your models here.
class MyQuestion (models.Model):
    question_text=models.CharField(max_length=100)
    pub_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text
class MyChoice (models.Model):
    question=models.ForeignKey(MyQuestion, on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=100)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollster/polls/views.py
from django.shortcuts import render
from polls.models import MyChoice,MyQuestion


# Create your views here.
def index(request):
    latest_question_list=MyQuestion.objects.order_by('-pub_date')[:5]
    context={'latest_question_list':latest_question_list,}
    return render(request,'polls/index.html',context)

def detail(request,question_id):
    try:
        question=MyQuestion.objects.get(pk=question_id)
    except:
        raise http404('question Doesn\'t exist')
    return render(request,'polls/result.html',{'question':question})

pollster/templates/base.html
<!DOCTYPE html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Pollster {% block title %} {%endblock%}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <div class ="container">
            {% block body %} {%endblock%}   
        </div>
          
    </body>
</html>

pollster/templates/polls/index.html
{% extends 'base.html'%}
{% block body %}
     {% if latest_question_list  %}
        {% for questions in latest_question_list  %}
        <h1>{{questions.question_text}}</h1>  
        <a href=" {% url 'polls:detail' questions.id %}">Vote Now</a>     
        {% endfor %}
     {% else %}
     <p>NO QUESTIONS YET</p>
     
     {% endif %}
{% endblock %}

pollster/templates/polls/result.html
{% extends 'base.html' %}
{% block title%}
    results
{% endblock %}
{% block body%}
    {% for choice in question.mychoice_set.all %}
        <p>{{choice.choice_text}}</p>
    {% endfor %}
{% endblock %}